"""empty message

Revision ID: a3f7a4dc11f5
Revises: ac15dec3cdf3
Create Date: 2018-03-12 20:46:33.939702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f7a4dc11f5'
down_revision = 'ac15dec3cdf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LEARN_WORD',
    sa.Column('KEYWORD', sa.String(length=200), nullable=False),
    sa.Column('MESSAGE', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('KEYWORD')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LEARN_WORD')
    # ### end Alembic commands ###
