"""empty message

Revision ID: ac15dec3cdf3
Revises: 
Create Date: 2018-03-12 14:02:40.576222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac15dec3cdf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PictureDate',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Uuid', sa.String(length=64), nullable=True),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PictureDate')
    # ### end Alembic commands ###
